language: node_js
node_js:
  - '10'
  - '9'
  - '8'
  - '7'
after_script:
  - './node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov'
cache:
  directories:
    - node_modules
